name: Versioning and Documentation
on:
  #push:
  #  branches: [ "release" ]
  #  paths-ignore:
  #    - 'docs/**'
  #    - 'README.md'
  pull_request_target:
    types:
      - closed 
    branches: [ "release" ]
  workflow_dispatch:
env:
  PROJECT: verkadaModule
jobs:
  Patch:
    if: ${{ !(startsWith(github.head_ref, 'minor/') && github.event.pull_request.merged == true) && !(startsWith(github.head_ref, 'major/') && github.event.pull_request.merged == true) }}
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/release.ps1)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
          branch: release
          push_options: '--force'
  Minor:
    if: startsWith(github.head_ref, 'minor/') && github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/release.ps1 minor)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
          branch: release
          push_options: '--force'
  Major:
    if: startsWith(github.head_ref, 'major/') && github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/release.ps1 major)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
          branch: release
          push_options: '--force'